//Module included in the following assemblies:
//
// * deploying-sandboxed-container-workloads-peer-pods.adoc

:_content-type: CONCEPT
[id="sandboxed-containers-prerequisites-peer-pods_{context}"]
= Prerequisites

Before you install {sandboxed-containers-first} and enable peer-pods, you must meet the following requirements:

* You have {product-title} {product-version} installed on AWS or Azure.
* You have installed the OpenShift CLI (oc).
* You have access to the cluster as a user with the cluster-admin role.

[id="sandboxed-containers-peer-pods-resource-requirements_{context}"]
== Resource requirements for peer-pods in {sandboxed-containers-first}

A peer-pod uses resources in two locations:

* The Kubernetes worker node. The worker node stores metadata, Kata shim resources (`containerd-shim-kata-v2`), remote-hypervisor (`cloud-api-adaptor`) resources, and the tunnel setup between the worker nodes and the peer-pod VM.
* The cloud instance. This is the actual peer-pod VM running in the cloud.

The CPU and memory resources used in the Kubernetes worker node are handled by the a link:https://kubernetes.io/docs/concepts/scheduling-eviction/pod-overhead/[pod overhead] included in the RuntimeClass (`kata-remote-cc`) definition used for creating peer-pods.

The total capacity of the peer-pod VMs running in the cloud is defined as Kubernetes Node extended resources. This enables the Kubernetes scheduler to handle capacity tracking and accounting. The extended resource is named `kata.peerpods.io/vm`, and defines the maximum number of peer-pods that you can create in the cluster.

A link:https://https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/[mutating webhook] removes any resource-specific entries from the pod specifications and adds them to the peer-pods extended resources. This enables the Kubernetes scheduler to account for these extended resources, ensuring the peer-pod is only scheduled when resources are available.

The mutating webhook modifies a Kubernetes pod as follows:

*  The mutating webhook checks the pod for the expected `RuntimeClassName` value, specified in the `TARGET_RUNTIME_CLASS` environment variable. If the value in the pod specification does not match the value in the `TARGET_RUNTIME_CLASS`, the webhook exits without modifying the pod.
* If the `RuntimeClassName` values match, the webhook makes the following changes to the pod spec:
+
. The webhook removes every resource specifications from the resources field of all containers and init containers in the pod.
. The webhook adds the extended resource (`kata.peerpods.io/vm`) to the spec by modifying the resources field of the first container in the pod. The extended resource `kata.peerpods.io/vm` is used by the Kubernetes scheduler for accounting purposes.
. The webhook adds an annotation to the pod that specifies the instance type that is used when the VM is created in the cloud environment.

[NOTE]
====
The mutating webhook excludes specific system namespaces in {product-title} from mutation. If a peer-pod is created in those system namespaces, then resource accounting using Kubernetes extended resources will not work unless the pod spec includes the extended resource.
+
As a best practice, define a cluster-wide policy to only allow peer-pod creation in specific namespaces.
====
