//Module included in the following assemblies:
//
// * deploying-sandboxed-container-workloads-peer-pods.adoc

:_content-type: CONCEPT
[id="sandboxed-containers-prerequisites-peer-pods-azure_{context}"]
= Prerequisites for peer-pods using Azure

If you are using Azure to create peer-pods, you must ensure the following requirements:

* Your {product-title} cluster must be installed on Azure, with at least one worker node.
* You have access to the following credentials and subscription details:
+
--
** `AZURE_SUBSCRIPTION_ID`
** `AZURE_CLIENT_ID`
** `AZURE_CLIENT_SECRET`
** `AZURE_TENANT_ID`
--
+
These are used to create additional cloud instances in the same virtual private cloud (VPC) of the cluster.
* You must have the Azure CLI tool installed and configured.
* You must enable cluster communication on ports 15150 and 9000.
+
You can enable these ports in the Azure web console or using the following commands:
+
[source,terminal]
----
$ INSTANCE_ID=$(oc get nodes -l 'node-role.kubernetes.io/worker' -o jsonpath='{.items[0].spec.providerID}' | sed 's#[^ ]*/##g')
AZURE_RESOURCE_GROUP=$(oc get infrastructure/cluster -o jsonpath='{.status.platformStatus.azure.resourceGroupName}')

AZURE_NSG_NAME=$(az network nsg list --resource-group $AZURE_RESOURCE_GROUP --query "[].{Name:name}" --output tsv)

AZURE_VNET_NAME=$(az network vnet list --resource-group $AZURE_RESOURCE_GROUP --query "[].{Name:name}" --output tsv)

AZURE_SUBNET_NAME=$(az network vnet subnet list --resource-group $AZURE_RESOURCE_GROUP --vnet-name $AZURE_VNET_NAME  --query "[].{Name:name} | [? contains(Name, 'worker')]" --output tsv)

# Get the OpenShift worker subnet ip address cidr

AZURE_SUBNET_PREFIX=$(az network vnet subnet show --name $AZURE_SUBNET_NAME --vnet-name $AZURE_VNET_NAME --resource-group $AZURE_RESOURCE_GROUP --query "addressPrefix" --output tsv)

# This is required for peer-pods shim to kata-agent communication
az network nsg rule create \
  --resource-group $AZURE_RESOURCE_GROUP \
  --nsg-name $AZURE_NSG_NAME \
  --name Allow-Kata-Agent-Internal \
  --access Allow \
  --protocol Tcp \
  --direction Inbound \
  --priority 112 \
  --source-address-prefixes $AZURE_SUBNET_PREFIX \
  --source-port-range "*" \
  --destination-address-prefixes $AZURE_SUBNET_PREFIX  \
  --destination-port-range 15150

# This is required for peer-pods tunnel setup
az network nsg rule create \
  --resource-group $AZURE_RESOURCE_GROUP \
  --nsg-name $AZURE_NSG_NAME \
  --name Allow-VXLAN-Internal \
  --access Allow \
  --protocol Tcp \
  --direction Inbound \
  --priority 111 \
  --source-address-prefixes $AZURE_SUBNET_PREFIX \
  --source-port-range "*" \
  --destination-address-prefixes $AZURE_SUBNET_PREFIX  \
  --destination-port-range 9000
----