:_content-type: ASSEMBLY
[id="sandboxed-containers-4-10-release-notes"]
= {sandboxed-containers-first} {sandboxed-containers-version} release notes
include::_attributes/common-attributes.adoc[]
include::_attributes/virt-document-attributes.adoc[]
:context: sandboxed-containers-release-notes

toc::[]

[id="sandboxed-containers-1-2-about-this-release"]
== About this release

These release notes track the development of {sandboxed-containers-first} {sandboxed-containers-version} alongside Red Hat {product-title} {product-version}.

This product was previously released as a Technology Preview product in {product-title} 4.9 and is now generally available and enabled by default in {product-title} 4.10.

[id="sandboxed-containers-1-2-new-features-and-enhancements"]
== New features and enhancements

[id="kata-metrics-rn"]
=== Kata specific metrics and dashboard

The {sandboxed-containers-operator} now deploys an osc-monitor daemonset. This enables the collection of metrics specific to workloads running in sandboxed containers (including metrics about the hypervisor and the Guest OS instances). In addition, a pre-configured dashboard provides insights into your {sandboxed-containers-first} components, such as the total number of lightweight VMs enabled in a cluster and the CPU/memory consumption per VM.
 All metrics, as well as the dashboard, are available in the web console. For more information, see xref:../sandboxed_containers/monitoring-sandboxed-containers.adoc#monitoring-sandboxed-containers[Monitoring {sandboxed-containers-first}].

[id="enhanced-logging-rn"]
=== Enhanced logging

Administrators can now collect enhanced logs for {sandboxed-containers-first} runtime components. Enhanced logs are available when the CRI-O log level is set to `debug`. These logs are collected by the must-gather tool, or can be viewed in the node journal.
//For more information, see xref:../sandboxed_containers/troubleshooting-sandboxed-containers.adoc#sandboxed-containers-enable-debug-logs_troubleshooting-sandboxed-containers[Enabling debug logs for {sandboxed-containers-first}].

[id="node-eligibility-rn"]
=== Check node eligibility to run {sandboxed-containers-first}

Administrators can now check the eligibility of cluster nodes to run {sandboxed-containers-first}. This feature uses the Node Feature Discovery (NFD) operator to detect  node capabilities. Eligible nodes are labeled with `feature.node.kubernetes.io/runtime.kata, and the {sandboxed-containers-operator} uses this label to select candidate nodes for installation.

The administrator must deploy the NFD operator to use this feature, create a specific *NodeFeatureDiscovery* custom resource, and enable `checkNodeEligibility' when creating the *KataConfig* custom resource.
//For more information, see the xref:../sandboxed_containers/deploying-sandboxed-container-workloads.adoc#deploying-sandboxed-containers-workloads_additional-resources[Additional resources for Deploying {sandboxed-containers-first} workloads].

[id="OSC-compatibility-with-CNV"]
=== {sandboxed-containers-first} compatibility with {VirtProductName}

Users can now run {sandboxed-containers-first} on clusters with {VirtProductName} when VMs are configured correctly. For more information, see 

[id="support-AWS-bare-metal"]
=== {sandboxed-containers-first} availability on AWS bare-metal (tech preview)

Users can now install {sandboxed-containers-first} on AWS bare-metal clusters. This feature is in tech preview and not fully supported. For more information, see xref:../sandboxed_containers/understanding-sandboxed-containers.adoc#understanding-sandboxed-containers[Understanding {sandboxed-containers-first}].

[id="sandboxed-containers-1-2-bug-fixes"]
== Bug fixes

* Previously, when running Fedora on {sandboxed-containers-first}, some packages required file access permission changes that {product-title} did not grant to containers by default. With this release, these permissions are granted by default. (link:https://bugzilla.redhat.com/show_bug.cgi?id=1915377[*BZ#1915377*])

* Previously, adding a value to `kataConfgPoolSelector` in the {product-title} web console populated `scheduling.nodeSelector` with an empty value. As a result, pods that used a `RuntimeClass` object with the value of `kata` could be scheduled to nodes without the Kata Containers runtime installed. With this release, only nodes labeled with the same label as defined in `kataConfgPoolSelector` will install the Kata Containers runtime. (link:https://bugzilla.redhat.com/show_bug.cgi?id=2019384[*BZ#2019384*])

* Previously, the {sandboxed-containers-operator} details page on Operator Hub was missing fields. In this release, these fields are no longer missing. (link:https://bugzilla.redhat.com/show_bug.cgi?id=2019383[*BZ#2019383*])

* Previously, creating multiple `KataConfig` custom resources resulted in a silent failure, with no error from the {product-title} web console notifying the user that creating more than one custom resource failed. With this release, the user receives an error when trying to create multiple custom resources. (link:https://bugzilla.redhat.com/show_bug.cgi?id=2019381[*BZ#2019381*])

* Previously, there were instances where the Operator Hub in the {product-title} web console did not display icons for an Operator. With this release, icons are always displayed. (link:https://bugzilla.redhat.com/show_bug.cgi?id=2019380[*BZ#9019380*])

[id="sandboxed-containers-1-2-known-issues"]
== Known issues

* If you are using {sandboxed-containers-first}, you might receive SELinux denials accessing files or directories mounted from the `hostPath` volume in an {product-title} cluster. These denials can occur even when running privileged sandboxed containers, since privileged sandboxed containers do not disable SELinux checks.
+
Following SELinux policy on the host guarantees full isolation of the host file system from the sandboxed workload by default, and provides stronger protection against potential security flaws in `virtiofsd` or QEMU.
+
If the mounted files or directories do not have specific SELinux requirements on the host, you can use local persistent volumes as an alternative. Files are automatically relabeled to `container_file_t`, following SELinux policy for container runtimes. See xref:../storage/persistent_storage/persistent-storage-local.adoc[Persistent storage using local volumes] for more information.
+
Automatic relabeling is not an option when mounted files or directories are expected to have specific SELinux labels on the host. Instead, you can set custom SELinux rules on the host in order to allow virtiofsd to access these specific labels. (link:https://bugzilla.redhat.com/show_bug.cgi?id=1904609[*BZ#1904609*])

[id="sandboxed-containers-1-2-asynchronous-errata-updates"]
== Asynchronous errata updates

Security, bug fix, and enhancement updates for {sandboxed-containers-first} {sandboxed-containers-version} are released as asynchronous errata through the Red Hat Network. All {product-title} {product-version} errata is https://access.redhat.com/downloads/content/290/[available on the Red Hat Customer Portal]. See the https://access.redhat.com/support/policy/updates/openshift[{product-title} Life Cycle] for more information about asynchronous errata.

Red Hat Customer Portal users can enable errata notifications in the account settings for Red Hat Subscription Management (RHSM). When errata notifications are enabled, users are notified via email whenever new errata relevant to their registered systems are released.

[NOTE]
====
Red Hat Customer Portal user accounts must have systems registered and consuming {product-title} entitlements for {product-title} errata notification emails to generate.
====

This section will continue to be updated over time to provide notes on enhancements and bug fixes for future asynchronous errata releases of {sandboxed-containers-first} {sandboxed-containers-version}.

[id="sandboxed-containers-1-2-0"]
=== RHEA-2021:3941 - {sandboxed-containers-first} {sandboxed-containers-version}.0 image release, bug fix,and enhancement advisory

Issued: 2021-10-21

{sandboxed-containers-first} release {sandboxed-containers-version}.0 is now available. This advisory contains an update for {sandboxed-containers-first} with enhancements and bug fixes.

The list of bug fixes included in the update is documented in the link:https://access.redhat.com/errata/RHEA-2021:3941[RHEA-2021:3941] advisory.
