:_content-type: ASSEMBLY
[id="sandboxed-containers-4-10-release-notes"]
= {sandboxed-containers-first} {sandboxed-containers-version} release notes
include::_attributes/common-attributes.adoc[]
include::_attributes/virt-document-attributes.adoc[]
:context: sandboxed-containers-release-notes

toc::[]

[id="sandboxed-containers-1-2-about-this-release"]
== About this release

These release notes track the development of {sandboxed-containers-first} {sandboxed-containers-version} alongside Red Hat {product-title} {product-version}.

This product was previously released as a Technology Preview product in {product-title} 4.9 and is now generally available and enabled by default in {product-title} 4.10.

[id="sandboxed-containers-1-2-new-features-and-enhancements"]
== New features and enhancements

[id="kata-metrics-rn"]
=== Kata specific metrics and dashboard

The {sandboxed-containers-operator} now deploys an osc-monitor daemonset. This enables the collection of metrics specific to workloads running in sandboxed containers (including metrics about the hypervisor and the Guest OS instances). In addition, a pre-configured dashboard provides insights into your {sandboxed-containers-first} components, such as the total number of lightweight VMs enabled in a cluster and the CPU/memory consumption per VM.
 All metrics, as well as the dashboard, are available in the web console. For more information, see xref:../sandboxed_containers/monitoring-sandboxed-containers.adoc#monitoring-sandboxed-containers[Monitoring {sandboxed-containers-first}].

[id="enhanced-logging-rn"]
=== Enhanced logging

Administrators can now collect enhanced logs for {sandboxed-containers-first} runtime components. Enhanced logs are available when the CRI-O log level is set to `debug`. These logs are collected by the must-gather tool, or can be viewed in the node journal.
//For more information, see xref:../sandboxed_containers/troubleshooting-sandboxed-containers.adoc#sandboxed-containers-enable-debug-logs_troubleshooting-sandboxed-containers[Enabling debug logs for {sandboxed-containers-first}].

[id="node-eligibility-rn"]
=== Check node eligibility to run {sandboxed-containers-first}

Administrators can now check the eligibility of cluster nodes to run {sandboxed-containers-first}. This feature uses the Node Feature Discovery (NFD) operator to detect  node capabilities. Eligible nodes are labeled with `feature.node.kubernetes.io/runtime.kata, and the {sandboxed-containers-operator} uses this label to select candidate nodes for installation.

The administrator must deploy the NFD operator to use this feature, create a specific *NodeFeatureDiscovery* custom resource, and enable `checkNodeEligibility' when creating the *KataConfig* custom resource.
//For more information, see the xref:../sandboxed_containers/deploying-sandboxed-container-workloads.adoc#deploying-sandboxed-containers-workloads_additional-resources[Additional resources for Deploying {sandboxed-containers-first} workloads].

[id="OSC-compatibility-with-CNV"]
=== {sandboxed-containers-first} compatibility with {VirtProductName}

Users can now run {sandboxed-containers-first} on clusters with {VirtProductName} when VMs are configured correctly. For more information, see

[id="support-AWS-bare-metal"]
=== {sandboxed-containers-first} availability on AWS bare-metal (tech preview)

Users can now install {sandboxed-containers-first} on AWS bare-metal clusters. This feature is in tech preview and not fully supported. For more information, see xref:../sandboxed_containers/understanding-sandboxed-containers.adoc#understanding-sandboxed-containers[Understanding {sandboxed-containers-first}].

[id="sandboxed-containers-1-2-bug-fixes"]
== Bug fixes

* Previously, using loop devices in a Kata Container was not possible due to missing kernel modules. With this release, these kernel modules are included in the package. (link:https://issues.redhat.com/browse/KATA-1334[*KATA-1334*])

* Previously, the {sandboxed-containers-operator} bundle was using an incorrect value for the `com.redhat.openshift.versions` label when building the container image. With this release, the Operator is available in the correct operator catalog for {product-title} version {product-version}. (link:https://issues.redhat.com/browse/KATA-1019[*KATA-1019*])

* Previously, the `MachineConfigPool` (MCP) created by the Operator to track the nodes with `Kata` runtime installed was not automatically removed on deletion of the `KataConfig` custom resource (CR). With this release, the deletion of `KataConfig` CR results in the removal of the `kata-oc` MCP. (link:https://issues.redhat.com/browse/KATA-1184[*KATA-1184*])

* Previously, when you created a `kataConfigPoolSelector` field and changed it, the {sandboxed-containers-operator} did not apply the change. With this release, the Operator acts on changes to the `kataConfigPoolSelector` field in the CRD and adapts installations of the runtime on nodes accordingly. (link:https://issues.redhat.com/browse/KATA-1190[*KATA-1190*])

* Previously, the `SourceImage` field was displayed on the web console and using the field had no effect on the installation. With this release, the unused `SourceImage` field is no longer displayed when creating `KataConfig` custom resource from the web console. (link:https://issues.redhat.com/browse/KATA-1015[*KATA-1015*])

[id="sandboxed-containers-1-2-known-issues"]
== Known issues

* If you are using {sandboxed-containers-first}, you might receive SELinux denials accessing files or directories mounted from the `hostPath` volume in an {product-title} cluster. These denials can occur even when running privileged sandboxed containers, since privileged sandboxed containers do not disable SELinux checks.
+
Following SELinux policy on the host guarantees full isolation of the host file system from the sandboxed workload by default, and provides stronger protection against potential security flaws in `virtiofsd` or QEMU.
+
If the mounted files or directories do not have specific SELinux requirements on the host, you can use local persistent volumes as an alternative. Files are automatically relabeled to `container_file_t`, following SELinux policy for container runtimes. See xref:../storage/persistent_storage/persistent-storage-local.adoc[Persistent storage using local volumes] for more information.
+
Automatic relabeling is not an option when mounted files or directories are expected to have specific SELinux labels on the host. Instead, you can set custom SELinux rules on the host in order to allow virtiofsd to access these specific labels. (link:https://bugzilla.redhat.com/show_bug.cgi?id=1904609[*BZ#1904609*])

* You might encounter an issue where `machine-config-operator` (MCO) pod changes to `CrashLoopBackOff` state and the "openshift.io/scc" annotation of the POD shows "sandboxed-containers-operator-scc" instead of the default "hostmount-anyuid".
+
If you encounter this issue, do the following steps:
+
. Change the `selinuxOptions` strategy by running the following command:
+
[source,terminal]
----
oc patch scc sandboxed-containers-operator-scc --type=merge --patch '{"seLinuxContext":{"type": "RunAsAny"}}'
----

. Scale a deployment by running the following command:
+
[source,terminal]
----
oc scale deployments/machine-config-operator -n openshift-machine-config-operator --replicas=0
----

. Scale a deployment again by running the following command:
+
[source,terminal]
----
oc scale deployments/machine-config-operator -n openshift-machine-config-operator --replicas=1
----

. Change the `selinuxOptions` strategy by running the following command:
+
[source,terminal]
----
oc patch scc sandboxed-containers-operator-scc --type=merge --patch '{"seLinuxContext":{"type": "MustRunAs"}}'
----

. Verify that the `hostmount-anyuid` SCC is applied to the `machine-config-operator` POD by running the following command:
+
[source,terminal]
----
oc get pods -n openshift-machine-config-operator -l k8s-app=machine-config-operator -o yaml | grep scc
openshift.io/scc: hostmount-anyuid
----
+
(link:https://bugzilla.redhat.com/show_bug.cgi?id=2057545[*BZ#2057545*])

* The {sandboxed-containers-operator} pods that utilize container CPU resource limits to increase the number of available CPUs for the pod may receive fewer CPUs than requested. If the functionality is available inside the container, you can diagnose CPU resources by `oc rsh <pod>` and running `lscpu`. 
+
[source,terminal]
----
# lscpu
CPU(s):                          16
On-line CPU(s) list:             0-12,14,15
Off-line CPU(s) list:            13
----
+
The list of available offline CPUs will likely change from run to run in an unpredictable manner.
+
As a workaround, you can use a pod annotation to request additional CPUs rather than setting a CPU limit. The method of allocating processors is different, and CPUs requested by means of pod annotation are not affected by this issue. Rather than setting a CPU limit, the following `annotation` should be added to the metadata of the pod:
+
[source,yaml]
----
metadata:
  annotations:
    io.katacontainers.config.hypervisor.default_vcpus: "16"
----
+
(link:https://issues.redhat.com/browse/KATA-1376[*KATA-1376*])

* The progress of the runtime installation is shown in the `status` section of the `kataConfig` CR. However the progress is not shown if all of the following conditions are true:

** The cluster has a machine config pool `worker` without any members (`machinecount=0`)
** No `kataConfigPoolSelector` is specified to select nodes for installation

+
In this case, the installation will start on the master nodes because the operator assumes it is a converged cluster where nodes have both master and worker roles. The `status` section of the `kataConfig` CR is not updated during the installation. (link:https://issues.redhat.com/browse/KATA-1017[*KATA-1017*])

* When creating the `KataConfig` CR and observing the POD status under `openshift-sandboxed-containers-operator` namespace, a huge number of restarts for monitor PODs is shown.  The monitor PODs use a specific SELinux policy that is installed as part of `sandboxed-containers` extension installation. The monitor POD gets created immediately, however the SELinux policy is not yet available, which results in a POD creation error, followed by a POD restart. When the extension installation succeeds, the SELinux policy will be available and the monitor POD will transition to `Running` state. This does not affect any functionality of the {sandboxed-containers-operator}. (link:https://issues.redhat.com/browse/KATA-1338[*KATA-1338*])

[id="sandboxed-containers-1-2-asynchronous-errata-updates"]
== Asynchronous errata updates

Security, bug fix, and enhancement updates for {sandboxed-containers-first} {sandboxed-containers-version} are released as asynchronous errata through the Red Hat Network. All {product-title} {product-version} errata is https://access.redhat.com/downloads/content/290/[available on the Red Hat Customer Portal]. See the https://access.redhat.com/support/policy/updates/openshift[{product-title} Life Cycle] for more information about asynchronous errata.

Red Hat Customer Portal users can enable errata notifications in the account settings for Red Hat Subscription Management (RHSM). When errata notifications are enabled, users are notified via email whenever new errata relevant to their registered systems are released.

[NOTE]
====
Red Hat Customer Portal user accounts must have systems registered and consuming {product-title} entitlements for {product-title} errata notification emails to generate.
====

This section will continue to be updated over time to provide notes on enhancements and bug fixes for future asynchronous errata releases of {sandboxed-containers-first} {sandboxed-containers-version}.

[id="sandboxed-containers-1-2-0"]
=== RHEA-2021:3941 - {sandboxed-containers-first} {sandboxed-containers-version}.0 image release, bug fix,and enhancement advisory

Issued: 2021-10-21

{sandboxed-containers-first} release {sandboxed-containers-version}.0 is now available. This advisory contains an update for {sandboxed-containers-first} with enhancements and bug fixes.

The list of bug fixes included in the update is documented in the link:https://access.redhat.com/errata/RHEA-2021:3941[RHEA-2021:3941] advisory.
